# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Replaced with modern one
name: pkgdown

on:
  push:
    branches: [main]
    paths:
      - 'R/**'
      - 'vignettes/**'
      - 'man/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
      - '_pkgdown.yml'
      - 'README.md'
      - 'NEWS.md'
      - '.github/workflows/pkgdown.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'R/**'
      - 'vignettes/**'
      - 'man/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
      - '_pkgdown.yml'
      - 'README.md'
      - 'NEWS.md'
      - '.github/workflows/pkgdown.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pkgdown-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
          # bump this to invalidate the cache when deps change oddly
          cache-version: 1

      # Build the site (works for both PRs and pushes)
      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      # Optional: add custom domain if you use one
      # - name: Add CNAME
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: echo "docs.yourdomain.com" > docs/CNAME

      # Upload built site as artifact for Pages (always)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      # Deploy to GitHub Pages only on push to main (not on PRs)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4