# .github/workflows/R-CMD-check.yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

name: R-CMD-check

on:
  push:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'
      - 'inst/**'
      - 'man/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
      - '.Rbuildignore'
      - '.github/workflows/R-CMD-check.yaml'
  pull_request:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'
      - 'inst/**'
      - 'man/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
      - '.Rbuildignore'
      - '.github/workflows/R-CMD-check.yaml'
  workflow_dispatch:

concurrency:
  group: r-cmd-check-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel',  http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true   # fast binaries on Linux
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          cache-version: 1        # bump to invalidate cache if needed
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
