# .github/workflows/test-coverage.yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Runs test coverage via covr and uploads directly to Codecov (tokenless for public repos)

name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run tests and upload coverage to Codecov
        run: covr::codecov()
        shell: Rscript {0}

      - name: Show coverage summary
        run: |
          Rscript -e 'cov <- covr::package_coverage();
                      cat("\nOverall Coverage:\n");
                      print(cov);
                      cat("\nCoverage by File:\n");
                      print(covr::per_file(cov))'
        shell: bash

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
